### PR TITLE
Docs/legacy flag

### LINKED ISSUE #157: Update browsers supported
The postcss configuration currently is configured for IE10 in legacy mode. This can be updated to IE11.

https://github.com/dojo/cli-build-app/blob/3213b6ba2886321229b431ddfc4f5469d5fd5c46/src/base.config.ts#L165

Additionally, the README should indicate what browsers are supported with and without the `--legacy` flag.

### PR DESCRIPTION
**Pull request by aciccarello**
Adds a a note to the readme about which browsers are supported and how to enable IE11 support. I'm not confident about the description so please make suggestions.

Resolves #157

### CODE REVIEW

**Comment by agubler** [comment]
@aciccarello Can we for now just update the README?

**Comment by aciccarello** [comment]
@agubler Should the readme say IE11 or IE10?

**Comment by agubler** [comment]
@aciccarello IE11

**Comment by agubler** [comment]
@aciccarello ping! would like to get this merged with just the readme updates, if you have time to update the PR 😄

**Comment by aciccarello** [comment]
Yep, planning on cleaning this up today.

**Comment by aciccarello** [comment]
That's odd, Cypress failed to run at all.

**Pull request merged**
