### PR TITLE
Update logger.ts to point to package.json for cli-build-app

### PR DESCRIPTION
**Pull request by jamesvhays**
Previously pointed to package.json of the project cli-build-app is installed in.

### CODE REVIEW

**Comment by matt-gadd** [comment]
Thanks for the contribution! Unfortunately due to some slight difference between running and testing, the package.json doesn't live in the same folder between them, which is why the build is failing. Do you think you could try replacing `__dirname` with https://github.com/sindresorhus/pkg-up?

**Comment by jamesvhays** [comment]
@matt-gadd sure, I can check that out.

**Comment by matt-gadd** [comment]
@jamesvhays awesome! thanks.

**Comment by jamesvhays** [comment]
@matt-gadd I ended up just passing the __dirname argument to the package that was originally in there. Should have done that the first time!

**Comment by matt-gadd** [comment]
@jamesvhays ha perfect! finally we'll be able to know what version people are using when they post a screenshot with problems 😄. This will make it into the 4.0.0 release next week, thanks for the contribution ⭐️

**Pull request merged**
