### PR TITLE
Use the fallback plugin for the express server

### PR DESCRIPTION
**Pull request by umaar**
Just so you can navigate to `localhost:9999/non/existant/path` and hit index.html

Resolves: https://github.com/dojo/dojo.io/issues/285#issuecomment-357300031 which includes all details of this feature.

### CODE REVIEW

**Comment by matt-gadd** [comment]
@umaar @mwistrand this looks good to me, but what do we do for the in memory mode?

**Comment by umaar** [comment]
Thanks both! I changed it to use `connect-history-api-fallback` instead, looks good!

@mwistrand - you know that code snippet you pasted above, had you just got that from a random example? Because it seems this is enough: `app.use(history());`? (It defaults to `index.html`)

**Comment by umaar** [comment]
@agubler noticed a good bug! Resource URLs are relative, not absolute.

This URL is requested: `http://localhost:4000/path/main.css`

On this page: `http://localhost:4000/path/`

I think it would make sense use absolute URLs like `<link href="/main.css" rel="stylesheet">`

Then Ant pointed out we should also think about lazily loaded bundles, since the URLs for those will be relative also!

**Comment by mwistrand** [comment]
@umaar The rewrite is necessary to take care of dealing with relative paths, which you've already pointed out as being problematic. If I just use `fallback()` and then navigate to `/deeply/nested/parent/child/grandchild`, the assets would be delivered as `/deeply/nested/parent/child/grandchild/{main.css|runtime.js|main.js}`. So some sort of URL rewriting will be necessary in order to ensure all paths are delivered correctly.

Changing the assets to use absolute paths could work with `--serve`, but will not work in a production build that's not hosted at the site root. I haven't given this the thought it deserves, but you and Ant are right that we will need to account for chunks created via the `bundles` option in the `.dojorc`.

**Comment by agubler** [comment]
@umaar What's the plan with this?

**Comment by umaar** [comment]
@agubler I would appreciate some more guidance with what exactly is needed to get all this working, considering there is the issue of sites which are not hosted at the site root and about the  lazily loaded bundles issue! Maybe if you do happen to have a clearer understanding, I could chat to you about this one?

**Comment by agubler** [comment]
Closing for now, this will need to be re-visited.

**Pull request closed without merging**
