### PR TITLE
Update compression-webpack-plugin and use it for brotli compression (fixes: #415)

### PR DESCRIPTION
**Pull request by willstott101**
Since newer node supports brotli compression natively, we're able to simplify our compression dependencies.

See #415 for discussion.

### CODE REVIEW

**Comment by willstott101** [comment]
Ah whoops... package.lock is using my companies internal npm... 1 minute

**Comment by matt-gadd** [comment]
@willstott101 rapid, thank you 👍 . I think we can probably land this in a patch release given it technically isn't a breaking change. cc @agubler

**Comment by matt-gadd** [comment]
@willstott101 this should be released in `7.0.2` if you want to give it a try? thanks again!

**Comment by willstott101** [comment]
oops... I tried it out and it's borken. Patch incoming

**Pull request merged**
